# Generated by Django 3.2.5 on 2021-08-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='thumbnail',
            field=models.CharField(max_length=300, verbose_name='이미지_url'),
        ),
    ]
