# Generated by Django 3.2.5 on 2021-08-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_season_painting'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_celebrity',
            name='title',
            field=models.CharField(default='', max_length=32, verbose_name='제목'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review_celebrity',
            name='space_name',
            field=models.CharField(max_length=32, verbose_name='장소'),
        ),
    ]
